
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: adilet.2005
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true